language: php

php:
    - 5.6.26
    - 7.0
    - 7.1
    - hhvm

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false

before_script:
    - composer self-update
    - composer remove --no-update --dev friendsofphp/php-cs-fixer
    - composer update --prefer-source `if [[ $COMPOSER_PREFER_LOWEST = true ]]; then echo "--prefer-lowest --prefer-stable"; fi`

script: vendor/bin/phpunit --coverage-clover build/clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

matrix:
    include:
        - php: 5.6.26
          env: COMPOSER_PREFER_LOWEST=true
    allow_failures:
        - php: hhvm

notifications:
    email: geloen.eric@gmail.com
